Changes for using action parameter of orkestra workflow executor
Azure/orkestra pull request #230
Opened 2021-05-12 23:03 UTC by davutkarabay

The action "install" and "delete" will be used for forward and reverse workflows respectively.

2021-05-13 05:47 UTC, jonathan-innis reviewed
Just to clarify, because I think I missed some of the conversation around it. Did we determine that the current workflow does not wait for the removal of the finalizer?

2021-05-13 16:53 UTC, nitishm commented on pkg/workflow/argo.go
> +	updateWorkflowTemplates(a.rwf, defaultExecutor(helmReleaseReverseExecutor, "delete"))
Let's define the action strings ("install" & "delete") as `type ExecutorAction string`  and create `const`s for each one.

2021-05-13 17:05 UTC, nitishm requested changes
Nit

2021-05-28 18:43 UTC, nitishm commented
@jonathan-innis No rush since you're OOF - but if you get bored can you take a look at why the e2e tests are failing. Since this is a pretty big change moving from the install only version of the executor image to the new version with both install and delete, it is possible that things might be broken or some incorrect assumptions might have been made.
@davutkarabay Can you compare the install code line-by-line and see if anything has changed in terms of underlying functions or timing delays etc since version v0.2.0?

2021-05-28 20:30 UTC, merged