Generate a unique prefix instead of initials when naming subcharts
Azure/orkestra pull request #283
Opened 2021-06-06 04:23 UTC by mahalrs

Closes #262

This change generates a unique prefix (using SHA-256 hash of application name) instead of initials when naming subcharts.

2021-06-07 19:34 UTC, mahalrs commented
@nitishm I'm not sure why e2e test is failing when I only replaced ToInitials() with GetHash(). Can you help me on this.

2021-06-07 20:04 UTC, nitishm commented
@mahalrs this is the error when you run it locally using 
`make clean && make dev && make test`
```
lastTransitionTime: "2021-06-07T20:00:22Z"                                                                                                                                                               
     message: |-                                                                                                                                                                                              
       Helm install failed: ServiceAccount "bookinfo-a82a4dac39a740d62d77081e3a1c040d134e5249002422d84740307d486572bb-details" is invalid: metadata.labels: Invalid value: "a82a4dac39a740d62d77081e3a1c040d134e5249002422d84740307d486572bb-details": must be no more than 63 characters
```

We might need to truncate the hash to 2 or 3 chars at most to keep the names under the max len limit enforced by DNS1123 (i.e. 63 chars)

2021-06-07 20:21 UTC, mahalrs commented
> @mahalrs this is the error when you run it locally using
> `make clean && make dev && make test`
> 
> ```
> lastTransitionTime: "2021-06-07T20:00:22Z"                                                                                                                                                               
>      message: |-                                                                                                                                                                                              
>        Helm install failed: ServiceAccount "bookinfo-a82a4dac39a740d62d77081e3a1c040d134e5249002422d84740307d486572bb-details" is invalid: metadata.labels: Invalid value: "a82a4dac39a740d62d77081e3a1c040d134e5249002422d84740307d486572bb-details": must be no more than 63 characters
> ```
> 
> We might need to truncate the hash to 2 or 3 chars at most to keep the names under the max len limit enforced by DNS1123 (i.e. 63 chars)

Should we use SHA-1 which is 40 characters.

2021-06-07 20:49 UTC, mahalrs commented
@nitishm We will use the SHA-256 and then after appending the ```scc.Metadata.Name``` to it, we will truncate it from left side to make sure ```hash + scc.Metadata.Name``` <= 63 chars.

For example, ```a82a4dac39a740d62d77081e3a1c040d134e5249002422d84740307d486572bb-details``` will become ~~a82a4dac3~~```9a740d62d77081e3a1c040d134e5249002422d84740307d486572bb-details```.

Let me know what you think.

2021-06-07 21:24 UTC, nitishm commented
That sounds pretty good. Add some test cases and also a boundary check where the app name itself is 63 chars. Though a corner case how would we handle that? Maybe truncate the name portion to accommodate part of the hash?

So it could be <partial-hash>-<truncated-name-to-accomodate-partial-hash>. But do this only for the corner case

2021-06-08 02:01 UTC, nitishm commented
@jonathan-innis Any thoughts on this one?

2021-06-08 02:06 UTC, mahalrs commented
@nitishm Max len limit 63 chars. So, at least 10 chars should come from hash, 1 char "-", and remaining from application name. So, max allowed application name is 52 chars. If > 52, truncate app name.

2021-06-08 07:03 UTC, jonathan-innis requested changes
Small readability comment, other than this looks great @mahalrs 🚀

2021-06-08 07:03 UTC, jonathan-innis commented on controllers/appgroup_reconciler.go
> +				hashAppChName := utils.GetHash(appCh.Metadata.Name)
Can we combine all these functions into a single `GetChartName` function? This will make things more readable

2021-06-08 18:11 UTC, nitishm commented on pkg/utils/chart.go
> +	// subchartNameMaxLen is the maximum length of a chart/subchart name.
```suggestion
	// subchartNameMaxLen is the maximum length of the subchart name.
```

2021-06-08 19:09 UTC, nitishm approved these changes
LGTM 🚀

2021-06-09 04:05 UTC, jonathan-innis approved these changes
🚀

2021-06-09 04:05 UTC, merged