Add unit tests for pkg/workflow/graph.go and pkg/workflow/utils.go
Azure/orkestra pull request #351
Opened 2021-06-26 04:52 UTC by mahalrs

Part of #316

2021-06-26 17:00 UTC, nitishm requested changes

2021-06-29 03:55 UTC, mahalrs commented on pkg/workflow/graph_test.go
> +func TestReverse(t *testing.T) {
@nitishm I will work on this tomorrow.

2021-06-29 04:01 UTC, nitishm commented on pkg/workflow/graph_test.go
> +func TestReverse(t *testing.T) {
Sync up with @jonathan-innis on slack as we might need to rewrite the reversal logic. In the meantime if you can find the root cause andpatch it, that would be great. But if it's a major flaw then let's work together to fix this

2021-07-02 20:42 UTC, nitishm commented
@mahalrs @jonathan-innis  let's get this merged in and we can address the concerns around the reversal issues when we rewrite it (as discussed earlier)

2021-07-02 20:43 UTC, nitishm approved these changes

2021-11-11 19:12 UTC, closed without merging