Pass executor template configuration through the `ApplicationGroup` spec
Azure/orkestra pull request #360
Opened 2021-07-09 16:09 UTC by mahalrs

Closes #188

2021-07-09 16:10 UTC, mahalrs commented
It not done yet but @nitishm can you have a look.

2021-07-13 18:00 UTC, nitishm commented
Hey @mahalrs hows this coming along? LMK if need any help

2021-07-14 19:27 UTC, jonathan-innis requested changes

2021-07-14 19:27 UTC, jonathan-innis commented on api/v1alpha1/appgroup_types.go
> +type Executor struct {
@nitishm  Let me try and understand the scenario here, is the idea that someone will customize the executor/docker image per-application group? What is the viable scenario for this? Can we not use a single docker image and then dynamically adjust the checks we do within that executable?

2021-09-23 06:12 UTC, closed without merging