API spec changes to support configuring workflow executors
Azure/orkestra pull request #380
Opened 2021-09-01 21:45 UTC by nitishm

Addresses #379

Signed-off-by: Nitish Malhotra <nitish.malhotra@gmail.com>

2021-09-02 18:55 UTC, nitishm commented
@jonathan-innis we can merge this in rather than have you fork from my branch. Adding these API changes should be benign (I think). WDYT? That way you can just work off of main

2021-09-02 19:06 UTC, jonathan-innis requested changes

2021-09-02 19:06 UTC, jonathan-innis commented on api/v1alpha1/appgroup_types.go
> +	DAG `json:",inline"`
nit: newline here

2021-09-02 19:06 UTC, jonathan-innis commented on api/v1alpha1/appgroup_types.go
> +	Image string `json:"image,omitempty"`
nit: newline here

2021-09-02 19:06 UTC, jonathan-innis commented on api/v1alpha1/appgroup_types.go
> +	Type ExecutorType `json:"type,omitempty"`
Can you specify the `kubebuilder:enum` annotation here?

2021-09-02 19:06 UTC, jonathan-innis commented on api/v1alpha1/appgroup_types.go
> +	HelmReleaseExecutor ExecutorType = "helmrelease"
nit: include newlines here

2021-09-02 19:07 UTC, jonathan-innis commented
> @jonathan-innis we can merge this in rather than have you fork from my branch. Adding these API changes should be benign (I think). WDYT? That way you can just work off of main

Yes, in general, I agree that merging these changes is benign

2021-09-03 22:46 UTC, merged

2021-09-03 22:46 UTC, jonathan-innis reviewed
🚀